tap "homebrew/bundle"

brew "eza"
brew "fastfetch"
brew "ffmpeg"
brew "gh"
brew "git"
brew "glow"
brew "helix"
brew "mas"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "uv"
brew "yazi"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "ghostty"
cask "zed"

cask "font-jetbrains-mono-nerd-font"

# Mac App Store
mas "Bear", id: 1091189122
mas "Craft", id: 1487937127
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Velja", id: 1607635845
mas "Xcode", id: 497799835
